-- CRIA O BANCO DE DADOS
CREATE DATABASE SENSOR;
-- SELECIONA O BANCO CRIADO
USE SENSOR;
-- CRIA TABELA CHAMADA DADOS COM OS CAMPOS DEFINIDOS 
CREATE TABLE `dados` (
  `ID` int NOT NULL AUTO_INCREMENT Primary Key,
  `Poten` varchar(10) NOT NULL,
  `Data` date NOT NULL,
  `Hora` time NOT NULL
);